server:
  port: 9091
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    dynamic:
      primary: master
      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      hikari:
        minimum-idle: 4  # 设置连接池的最小空闲连接数
        maximum-pool-size: 20  # 设置连接池的最大连接数
        connection-init-sql: SELECT 1  # 设置连接初始化的 SQL，验证连接是否有效
        connection-test-query: SELECT 1  # 设置连接池空闲连接的验证查询
        validation-timeout: 3000  # 设置验证查询的超时时间，单位：毫秒
        max-lifetime: 1800000  # 设置连接池中连接的最大生命周期，单位：毫秒
        idle-timeout: 600000  # 设置空闲连接的超时时间，单位：毫秒（默认10分钟）
        time-between-eviction-runs-millis: 30000  # 每30秒检查一次空闲连接
        min-evictable-idle-time-millis: 60000  # 空闲连接超过60秒会被丢弃
      datasource:
        master: #${SERVER_ADDRESS}
          url: jdbc:mysql://${SERVER_ADDRESS}:3307/xf-boot-base?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password:
          driver-class-name: com.mysql.cj.jdbc.Driver
          hikari:
            minimum-idle: 4  # 主数据源的最小空闲连接数
            maximum-pool-size: 20  # 主数据源的最大连接数
  cloud:
    nacos:
      discovery: #注册中心
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PWD:nacos}
        namespace: 74193cd9-fac4-4f2a-addc-47c60508b15c
        # cluster-name: DEFAULT  # 集群名称，保持一致
    loadbalancer: #开启负载均衡
      nacos:
        enabled: true
      retry:
        enabled: true # 启用负载均衡重试机制 负载均衡策略默认为轮询，想要修改策略新版本中需要手动java代码配置，新版本中配置文件的方式不支持了,更灵活但略复杂
    stream: #消息中间件
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          producer-out-0:
            producer:
              group: output_1
      bindings:
        producer-out-0:
          destination: topic0
        producer-out-1:
          destination: topic1
    sentinel: #流量控制中心
      transport:
        dashboard: localhost:8089 # sentinel-dashboard地址
        port: 8721
      eager: true
      filter:
        enabled: true

seata:
  server:
    address: 127.0.0.1:8091
  tm:
    default-transaction-manager-type: AT   # 默认使用 AT 模式
    default-timeout: 30000  # 设置全局事务超时
  application-id: ${spring.application.name}  # 这里是应用的唯一标识，可以根据你的服务名称设置
  tx-service-group: dubbo_tx_group  # 事务分组名称，确保每个 Dubbo 服务的 tx-service-group 一致
  registry:
    type: nacos  # 注册中心类型，如 nacos，若使用其他注册中心需要调整
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PWD:nacos}
      namespace: 581b3f92-be53-4537-b777-885ce60d07e9
      group: SEATA_GROUP
  config:
    type: nacos
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PWD:nacos}
      namespace: "581b3f92-be53-4537-b777-885ce60d07e9"
      group: SEATA_GROUP
      data-id: "seata-server.properties"
  service:
    grouplist:
      default: ${seata.address:127.0.0.1}:8091
    enable-degrade: false
    disable-global-transaction: false
  enabled: true

logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug