server:
  port: 9092
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: http-cloud-consumer
  cloud:
    stream: #消息中间件
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings:
          consumer0-in-0:
            consumer:
              messageModel: CLUSTERING
          consumer1-in-0:
            consumer:
              messageModel: CLUSTERING
      bindings:
        consumer0-in-0:
          destination: topic0
          group: clustering-consumer
        consumer1-in-0:
          destination: topic1
          group: clustering-consumer
    sentinel: #流量控制中心
      transport:
        dashboard: localhost:8089 # sentinel-dashboard地址
        port: 8720
      eager: true
      filter:
        enabled: true
    nacos:
      config: #配置中心
        server-addr: 127.0.0.1:8848
        prefix: http-cloud
        username: nacos
        password:
        namespace: 74193cd9-fac4-4f2a-addc-47c60508b15c
#      discovery: #注册中心
#        server-addr: 127.0.0.1:8848
#        username: nacos
#        password:
#        namespace:
#    loadbalancer: #开启负载均衡
#      nacos:
#        enabled: true
#      retry:
#        enabled: true # 启用负载均衡重试机制 负载均衡策略默认为轮询，想要修改策略新版本中需要手动java代码配置，新版本中配置文件的方式不支持了,更灵活但略复杂

  config:
    import: #指定加载配置的方式以及文件
      - nacos:http-cloud-producer.yaml

#打开 Sentinel 对 Feign 的支持
feign:
  sentinel:
    enabled: true

#seata:
#  enabled: true
#  application-id: ${spring.application.name}
#  tx-service-group: ${spring.application.name}-tx-group
#  config:
#    type: nacos
#    nacos:
#      serverAddr: 117.72.35.70:8848
#      dataId: "seata.properties"
#      username: 'nacos'
#      password: 'nacos'
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      username: 'nacos'
#      password: 'nacos'

logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug
#    org.springframework.cloud.stream: DEBUG
#    org.springframework.integration: DEBUG